/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package officeOlympics;

import officeOlympics.backend.JSONReader;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        try {
            JSONReader jsonReader = new JSONReader("data.json");
            System.out.println(jsonReader.getString("name"));
            System.out.println(jsonReader.getInt("age"));
            System.out.println(jsonReader.getString("lastName"));
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }
}
